feat: support csv files and add dataset csv view
graasp/graasp-insights pull request #165
Opened 2021-04-28 11:59 UTC by Painguin

Support csv and xlsx file formats. A Dataset with a csv and xlsx format is converted into an array of json objects for its use in the app.

In `DatasetScreen.js`, one can select between a json view and a csv (tabular) view. The csv view is only shown if the dataset supports it (array of json objects).

When exporting a dataset, one can select between the json a csv (if dataset supports it) format.

The generic algorithms (`hash fields`, `suppress fields`, `shuffle fields`) should all work with imported csv's (after generating a schema from them)

2021-04-28 13:53 UTC, pyphilia requested changes
It works really well! I left some comments, feel free to pin me for questions!

2021-04-28 13:53 UTC, pyphilia commented on src/components/dataset/DatasetScreen.js
> +            <Grid item xs={showTabular && !isGraasp ? 10 : 6}>
Can it be tabular and graasp?

2021-04-28 13:53 UTC, pyphilia commented on src/components/dataset/DatasetScreen.js
> +                  this.renderTabularView()
Would it be clearer to have a separated component for the table view?

2021-04-28 13:53 UTC, pyphilia commented on src/components/dataset/DatasetScreen.js
> +          {t("The dataset can't be displayed as a csv.")}
Maybe I would just disable to table view button if the dataset cannot be displayed as a table.

2021-04-28 13:53 UTC, pyphilia commented on test/dataset.test.js
> +    'Add, delete CSV dataset',
Add a test for xlsx as well?

2021-04-28 13:53 UTC, pyphilia commented on test/dataset.test.js
> +    'Add, delete CSV dataset',
Should you add tests for the view as well?

2021-04-29 13:07 UTC, Painguin commented on public/app/listeners/loadDataset.js
> +const XLSX = require('xlsx');
Most of the examples I've seen online use either `XLSX` or `xlsx`. Should I still go with `Xlsx`?

2021-04-30 14:33 UTC, Painguin commented on public/app/listeners/loadDataset.js
> +    isTabular = validateSchema(jsonContent, ARRAY_OF_JSON_SCHEMA);
Two corrections: we have to look if the data root type is an array and if each of the elements is an object. When modifying a dataset through the dataset screen and when creating a new result (after executing an algorithm), the isTabular value is recomputed again. So the only issue would be if the user goes himself in the directory to modify the dataset or if it gets corrupted somehow.

The alternative you propose is what I was going for first. But when we export a dataset, I need to check if the dataset is tabular to propose the `Export as CSV` option and that implies fetching the dataset content from the backend. This looked cumbersome and went with the `isTabular` solution

2021-05-03 11:10 UTC, pyphilia approved these changes
Nice! Just two minors comments, and you can merge!

2021-05-07 14:45 UTC, merged