13/get dataset
graasp/graasp-insights pull request #25
Opened 2020-09-23 12:51 UTC by pyphilia

This PR links previous PR (dataset load, python execution, datasets list) and saves the datasets in a local db (lowdb).

close #13

2020-09-23 14:17 UTC, pyphilia commented on public/app/listeners/executePythonAlgorithm.js
> +        })
Create util function to push files (similarly to `loadDataset.js`)

2020-09-23 15:01 UTC, pyphilia commented on src/components/Datasets.js
> +            <Typography variant="h6">{name}</Typography>
Link with `DatasetScreen.js`

2020-09-23 15:39 UTC, hagoptaminian requested changes
@pyphilia nice work! I left some comments. in addition to those, please review the 'Sort By' functionality to resolve the bug that we observed where datasets in the table seem to become duplicated. I have some other comments which I think I will add as issues, after I review this code one more time (once you make the changes discussed here).

2020-09-23 15:39 UTC, hagoptaminian commented on src/components/Datasets.js
> +                <TableCell align="right" />
Add title to this part of the table, something like 'Quick Actions'

2020-09-23 15:39 UTC, hagoptaminian commented on public/app/listeners/executePythonAlgorithm.js
> +          id,
...or set `lastModified` to be the same as `createdAt`

2020-09-23 15:39 UTC, hagoptaminian commented on src/components/dataset/DatasetReader.js
> +      return <span>{t('This file is too huge to be displayed.')}</span>;
(1) Let's use a Typography element instead of a span.
(2) 'This file is too **big** to be displayed.'

2020-09-23 15:39 UTC, hagoptaminian commented on src/config/messages.js
> +const ERROR_GETTING_DATASET_MESSAGE = 'There was an error getting the dataset';
let's use _retrieving_ instead of _getting_ (more formal)

2020-09-24 08:59 UTC, pyphilia commented
In this commit https://github.com/graasp/graasp-insights/pull/25/commits/bf060a600fac9c010f4ea25422926d0df23eb962, I applied the requested changes. I added a new quick action "view" which leads to the `DatasetScreen.js` component, allowing us to view the json content in the interface.

2020-09-24 13:24 UTC, merged