refactor: handle toastr notifications in middleware
graasp/graasp-insights pull request #32
Opened 2020-09-29 13:01 UTC by pyphilia

This PR aims to refactor toastr notifications (compared to graasp-desktop) in a common middleware.

In doing so, `types` had to be accessible from the `public` folder. I therefore took this opportunity to handle duplicates of `channels.js`, `errors.js`, `messages.js`, etc. With this PR, these files are located in `src/shared` and are duplicated in `public/shared` before each `yarn start` and `yarn mocha` (inspired by https://medium.com/@johndyer24/building-a-production-electron-create-react-app-application-with-shared-code-using-electron-builder-c1f70f0e2649). 

The main changes implied:
1. Actions do not create the action objects, listeners do. Success actions are unchanged. Error actions have the following shape 
```
{
  type: GET_DATASET_ERROR, 
  error: ERROR_GENERAL,
  payload?: {somedata}
}
```
where payload can be used to customize the message error or change data in the reducer.

2. `channels.js`, `errors.js`, `messages.js` and such are only edited in `src/shared` (changes are reported automatically)
3. `toastrMiddleware.js` receives all dispatched actions, one just needs to catch them in the switch when a notification is required.

With the current changes, we end up with relatively repetitive and simple actions. We might create a utility function to generate them if necessary. 

Duplicating files is not the ideal solution. Another solution I looked into was to use the public folder in a react way https://create-react-app.dev/docs/using-the-public-folder/ but it does not seem to support dynamic import (such as `import x from 'PUBLIC_URL+filename'`).

2020-10-16 16:05 UTC, juancarlosfarah requested changes
Very nice! Just some minor comments and questions.

2020-10-16 16:05 UTC, juancarlosfarah commented on package.json
> +    "mocha": "concurrently \"yarn:prepare\" \"env-cmd -f ./.env.test react-scripts start\" \"wait-on http://localhost:3000 && mocha --require @babel/register \"test/**/*.test.js\"\"",
Don't think you need the `:` between `yarn` and `prepare`.

2020-10-22 12:52 UTC, pyphilia commented
I applied the changes and rebased on the master to include all the changes.

2020-10-27 15:17 UTC, pyphilia commented
I've rebased again, it would be nice to merge this one!

2020-10-28 08:55 UTC, hagoptaminian approved these changes
@pyphilia this looks good to me. nice work.

2020-10-28 14:22 UTC, merged