feat: add settings tab with language selection
graasp/graasp-insights pull request #33
Opened 2020-10-01 13:43 UTC by Painguin

close #21.

Creates a Settings tab with language selection.

2020-10-02 12:26 UTC, pyphilia requested changes
Really nice! Here some minor comments.

2020-10-02 12:26 UTC, pyphilia commented on src/components/Settings.js
> +export default withRouter(TranslatedComponent);
Do you need `withRouter` in this component?

2020-10-02 12:26 UTC, pyphilia commented on src/config/messages.js
> +const ERROR_GETTING_LANGUAGE = 'There was an error getting the language.';
I think we are going with `retrieving` here.

2020-10-02 12:26 UTC, pyphilia commented on src/langs/fr.json
> +    "KB": "KB",
Change to `Ko`

2020-10-07 11:47 UTC, pyphilia approved these changes

2020-10-07 13:27 UTC, hagoptaminian requested changes

2020-10-07 13:27 UTC, hagoptaminian commented on src/langs/en.json
> +    "Danger Zone! Proceed with caution as changes to this section might lead to data loss.": "Attention ! Les modifications de cette section pourraient entraîner une perte de données.",
This is a French translation in `en.json`. Also, no space between 'Attention' and '!'

2020-10-07 13:32 UTC, hagoptaminian commented
@Painguin this looks good to me - left a small comment on a mistake in `en.json`. Otherwise, I don't think it's great the way the dropdown menu in the new component stretches across the entire page:

![Screen Shot 2020-10-07 at 3 28 13 PM](https://user-images.githubusercontent.com/19311953/95337087-cad32180-08b1-11eb-85c5-92f70064b256.png)

Maybe giving it width of 25% is better. Also, instead of a Menu item, I think it's nicer to have the settings accessible via a settings icon in the header, which when clicked on pops up a modal through which the user can adjust language (and in the future other) settings (that way they don't have to navigate away from the page they're on). This is similar to how Postman and other apps do it:

![Screen Shot 2020-10-07 at 2 02 08 PM](https://user-images.githubusercontent.com/19311953/95337266-f6eea280-08b1-11eb-82e9-16d1bc364934.png)

![Screen Shot 2020-10-07 at 2 02 43 PM](https://user-images.githubusercontent.com/19311953/95337349-0b329f80-08b2-11eb-81d9-1b5b85229f23.png)

2020-10-12 14:30 UTC, Painguin commented
Thank you for comment @hagoptaminian. I have modified the settings tab into a modal as you suggested.

2020-10-13 09:43 UTC, hagoptaminian approved these changes

2020-10-14 08:53 UTC, pyphilia requested changes
Nice work! Some minor comments and it can be merged.

2020-10-14 08:53 UTC, pyphilia commented on src/actions/settings.js
> +    toastr.error(ERROR_MESSAGE_HEADER, ERROR_GETTING_LANGUAGE);
You'll probably need `dispatch(flagGettingLanguage(false));` in the `catch` block as well. (same below)

2020-10-14 08:53 UTC, pyphilia commented on src/components/common/Header.js
> +    padding: '0px',
You can use `theme.spacing(0)` here.

2020-10-14 08:53 UTC, pyphilia commented on src/langs/en.json
> +    "Quick actions": "Actions rapides",
French translation here.

2020-10-14 08:53 UTC, pyphilia commented on src/reducers/settingsReducer.js
> +  switch (type) {
Maybe add the flags dispatch here.

2020-10-14 10:12 UTC, pyphilia approved these changes

2020-10-14 10:27 UTC, merged