35/change algo display
graasp/graasp-insights pull request #43
Opened 2020-10-15 09:04 UTC by Painguin

This PR changes the `Algorithms` tab to display a table of the available algorithms and creates an `Executions` tab from which you can select and run an algorithm on some dataset.

The algorithms table features a delete button (functional) and an edit button (non-functional).
For now, two algorithms are available. They might not reflect exactly what we want but more and more specific ones will be added in the future.   
On application startup, the presence of the default `graasp` algorithms are checked and added if not present.
The database now contains an entry for the algorithms with the required information.

A table of executions is planned and will be done in an other PR.

close #35.

2020-10-15 10:07 UTC, pyphilia requested changes
Very nice work! I like how you deal different programming languages.
You will surely need to rebase on my PR once it is merged.

2020-10-15 10:07 UTC, pyphilia commented on src/langs/fr.json
> +    "Load a dataset first": "Veuillez importer a dataset",
`un` instead of `a`

2020-10-15 13:16 UTC, hagoptaminian requested changes
@Painguin Nicely done! Left some comments, mostly on style/layout, and ensuring consistent display across tables. Let me know if anything is unclear.

2020-10-15 13:16 UTC, hagoptaminian commented on src/components/Executions.js
> +      </Main>
The use of the Grid system here is really overkill. Simplify to:

```JavaScript
<div className={classes.container}>
  <FormControl variant="outlined" className={classes.formControl}>
    <Select id="datasetSelect">...</Select>
  </FormControl>
  <FormControl variant="outlined" className={classes.formControl}>
    <Select id="algorithmSelect">...</Select>
  </FormControl>
  <Button
    variant="contained"
    color="primary"
    onClick={this.executeAlgorithm}
    className={classes.button}
  >
    {t('Execute')}
  </Button>
</div>;
```

where:

```JavaScript
  container: {
    width: '50%',
    margin: '0 auto',
    marginTop: theme.spacing(2),
  },
  formControl: {
    marginTop: theme.spacing(2),
    width: '100%',
  },
  button: { 
    display: 'block', 
    margin: '0 auto', 
    marginTop: theme.spacing(2) 
  },
```

2020-10-15 13:16 UTC, hagoptaminian commented on src/components/Executions.js
> +              <Typography>{t('Dataset')}</Typography>
Instead of this, within `FormControl`, use `InputLabel` as shown in the example here https://material-ui.com/components/selects/#select

2020-10-15 13:16 UTC, hagoptaminian commented on src/components/Executions.js
> +              <Typography>{t('Dataset')}</Typography>
Or alternatively `FormHelperText`, also in that example

2020-10-15 13:16 UTC, hagoptaminian commented on src/components/Executions.js
> +                  value={datasetId || ''}
Will the part after the `||` ever be reached? If there are no datasets, we are rendering the Alert, right? Look into it - if redundant, better to remove it.

2020-10-15 13:35 UTC, Painguin commented on src/components/Algorithms.js
> +  renderTable() {
That's a valid point. I think refactoring into a reusable component is good idea. An interesting component we could also use are [datagrids](https://material-ui.com/components/data-grid/rows/#data-grid-rows).

2020-10-16 11:28 UTC, Painguin commented on public/algorithms/default_anonymization.py
> +""" Anonymize a dataset: removes sensitive values and replaces names/ids by hashes """
I agree this should be way we present algorithms. But I will leave that one for now just for the sake of having more than one algorithm. I will modify the presented algorithms later in an other PR.

2020-10-19 09:01 UTC, Painguin commented
Thank you for your reviews!
I have abstracted the tables into a reusable component. It requires two props: 
- `columns`: array of columns that contains information about each column:
  - `columnName`
  - `sortBy`: field on which we sort the column (`undefined` if not sortable)
  - `field`: field corresponding to the value to display
  - `alignColumn`: alignment of the head/column name
  - `alignField`: alignment of the value field
  - `bold`: whether the column name is bold
- `rows`: array of objects with each required field for each row

Let me know what you think! @pyphilia @hagoptaminian

2020-10-19 09:17 UTC, pyphilia requested changes
I really like this refactor~ Here some minor comments.

2020-10-19 09:17 UTC, pyphilia commented on src/components/Results.js
> +    const rows = results.map((dataset) => {
I guess it should be called `result` instead of `dataset`.

2020-10-19 09:17 UTC, pyphilia commented on src/components/Results.js
> +        algorithmId,
Could we display the algorithm's name here instead of the id?

2020-10-19 09:18 UTC, pyphilia requested changes
I really like the refactor~ Here some comments.

2020-10-19 11:07 UTC, hagoptaminian commented
@Painguin this is looking great. love the latest additions. reviewing the files now, but in the meantime I have two comments:

1. make the 'Quick Actions' header consistent in font with the rest of the table headers
2. right now we are using two different Alert styles - in one case in the middle of the page, and in one case across the top. can we switch to using just one style? (up to you which)

2020-10-19 11:23 UTC, hagoptaminian approved these changes
One more comment in addition the above:

In Results.js, instead of 'Result from' being the ID of the Python algorithm, which has no meaning to and is never seen by the user, it's better to use the algorithm name

2020-10-20 07:47 UTC, hagoptaminian commented
@Painguin @pyphilia for me this looks good to merge

2020-10-20 08:24 UTC, merged