feat: edit dataset from interface
graasp/graasp-insights pull request #61
Opened 2020-11-02 16:21 UTC by pyphilia

close #41

2020-11-04 10:56 UTC, Painguin requested changes
Good feature! 

Each time I do some modification, the editor view is reset and everything is collapsed again. This can be very annoying when doing multiple small modifications. Is it possible not to reset the view? Maybe we still save the file after each change but we don't update the content with the reducer? I don't know if the JSON editor keeps the modifications or not in that case...

2020-11-04 10:56 UTC, Painguin commented on public/app/listeners/setDatasetFile.js
> +    const contentAsString = JSON.stringify(content);
This sets all the json content of the file into one line which is not visually pleasant when looking at the file itself. Use `JSON.stringify(content, null, 2)` instead to have indentation and all.

2020-11-04 10:56 UTC, Painguin commented on src/components/dataset/DatasetScreen.js
> +    const actions = parsedContent?.actions.filter((action) => action) || [];
If the actions are deleted, then there is an error on the `filter` call. Should be `parsedContent?.actions?.filter`

2020-11-04 13:00 UTC, hagoptaminian reviewed
nice feature and works well. agree with @Painguin's comment that it would be nice if we could stay in the section of the file we are editing after confirming an edit (rather than having it refresh and collapse). a few other comments:

1. we access this edit view via the `View dataset` quick action - what are we expecting to do with the `Edit dataset` one?

2. currently this is only enabled for original datasets loaded into the app - i.e. not for results generated from executions. was this intentional?

3. would be nice if when attempting to delete a key in the json, we get a prompt confirming the delete/saying it is irreversible

2020-11-04 13:09 UTC, pyphilia commented
Thank you for your reviews!

@hagoptaminian 
1 - Honestly I am not sure. Maybe we should have a same quick action for both view and edit. What do you think?
2 - Yes, I guess results shouldn't be editable unless they are set as datasets. If we could edit a result, then it would mislead the user about the processing the algorithm applied, don't you think?
3 - It would be nice indeed, I will add it.

2020-11-04 16:33 UTC, pyphilia commented
The collapsed elements remain after an update. 
The strategy was to avoid refreshing `DatasetScreen.js`, because it would re-render `JSONFileEditor.js` and thus reset the collapsing. Therefore, I only use the necessary properties in `DatasetScreen.js`,  `JSONFileEditor.js` and `DatasetInformationTable.js` to avoid unnecessary rendering (particularly in the main screen). That way, the table is also updating alongside the json file.

2020-11-05 08:28 UTC, hagoptaminian reviewed
looks good and works well! on our discussion above:

1. agreed that we should eliminate the Edit dataset icon (and have the current View dataset icon cover both)
2. good point. but I was thinking... imagine I ran a few algorithms on a dataset, and then I wanted to finalize the result, for example by deleting the appInstanceResources key in a dataset (because I don't need it, don't want to publish it)... it would be nice to be able to do this. of course, the user can still export the dataset and reload it via the Datasets tab, and edit it that way, but it's a bit of a longer process... so I'm leaning toward giving the users the ability to edit results as well.

2020-11-11 12:51 UTC, Painguin approved these changes
Good job @pyphilia! Specially on making the table reactive to the changes.

2020-11-11 12:51 UTC, Painguin commented on public/app/listeners/setDatasetFile.js
> +    }
This is a better way of handling missing files than checking the `ENOENT` error code :+1: We should do that everywhere

2020-11-11 12:51 UTC, Painguin commented on public/shared/messages.js
> +  'There was an error editing the dataset';
`ERROR_EDITING_DATASET_FILE_MESSAGE` is not used anywhere. I assume it got replaced by `ERROR_SETTING_DATASET_FILE_MESSAGE` and should be deleted

2020-11-11 12:51 UTC, Painguin commented on src/components/common/JSONFileEditor.js
> +        {...editProps}
I didn't know you could do that :open_mouth:

2020-11-11 12:51 UTC, Painguin commented on src/shared/messages.js
> +  'There was an error editing the dataset';
delete `ERROR_EDITING_DATASET_FILE_MESSAGE`

2020-11-11 14:16 UTC, merged