test: set up spectron
graasp/graasp-insights pull request #7
Opened 2020-08-26 09:13 UTC by pyphilia

This PR uses `"spectron": "11.0.0"` because the version `11.1.0` contains breaking changes and throws an error for every test.

2020-08-30 22:47 UTC, juancarlosfarah requested changes
Thanks for adding this. Just some minor recommendations. Otherwise all good from my end. Check with @hagoptaminian for merging.

2020-08-30 22:47 UTC, juancarlosfarah commented on src/config/selectors.js
> +export const QUIT_MENU_ITEM_ID = 'closeMenuItem';
Maybe consistency between `quit` and `close`?

2020-08-30 22:47 UTC, juancarlosfarah commented on test/menu.test.js
> +    'Displays correct navigation',
Try to keep `it` blocks starting with lower case, to differentiate from `describe` blocks. Not important, just a tip.

2020-09-04 06:47 UTC, hagoptaminian approved these changes
this looks good to me! ran `yarn mocha` locally and the tests are working

2020-09-04 07:09 UTC, merged