fix: clear dataset and result state
graasp/graasp-insights pull request #75
Opened 2020-11-11 15:25 UTC by pyphilia

close #66

2020-11-11 15:26 UTC, pyphilia commented on src/reducers/resultReducer.js
>  const INITIAL_STATE = Map({
Add flag.

2020-11-16 08:41 UTC, hagoptaminian approved these changes
looks good to me!

2020-11-17 09:28 UTC, Painguin requested changes
Looks good! I've been a lot more minimalist when clearing the state of algorithms (without flags/try-catch). Could you please add the missing things in clearAlgorithm to be consistent.

2020-11-17 10:23 UTC, Painguin approved these changes

2020-11-17 10:30 UTC, merged