54/test algorithms tab
graasp/graasp-insights pull request #99
Opened 2020-11-20 17:25 UTC by Painguin

Tests the `Algorithms.js`, `AddAlgorithm.js` and `EditAlgorithm.js` pages.

close #54 .

2020-11-23 13:42 UTC, pyphilia requested changes
Good job! What do you think of tests? :P If you have any feedback or comment about how we actually proceed let me know.

Maybe I would suggest to create a folder `algorithms` in `tests` and divide your big file into subfiles such as `editAlgorithm`, `addAlgorithm` as it will get even with our next features.. If a test does not belong to a single category let's also have a `common`/ `algorithm` file or something similar.

2020-11-23 13:42 UTC, pyphilia commented on test/algorithm.test.js
> +const menuGoTo = async (client, selector) => {
Place it in `utils.js`, and you could add a new `menuGoToAlgorithms` with the selector already set.

2020-11-23 13:42 UTC, pyphilia commented on test/algorithm.test.js
> +const verifyAlgorithm = async (client, algorithm) => {
Rename with something similar to `checkAlgorithmRowLayout`

2020-11-23 13:42 UTC, pyphilia commented on test/algorithm.test.js
> +  fileOption.click();
`await` missing

2020-11-23 13:42 UTC, pyphilia commented on test/algorithm.test.js
> +    'Correctly adds Graasp algorithms',
`Correctly initialize Graasp algorithms`

2020-11-23 13:42 UTC, pyphilia commented on test/algorithm.test.js
> +      const deleteButton = await client.$(
It might be worth checking it is the right algorithm you deleted.

2020-11-23 13:42 UTC, pyphilia commented on test/algorithm.test.js
> +    'Adding a non existing algorithm does not add it to database',
I would go for `Using an incorrect algorithm file leads to error`

2020-11-23 13:42 UTC, pyphilia commented on test/algorithm.test.js
> +    'Adds, edits and deletes and algorithm',
typo `an algorithm`

2020-11-23 13:42 UTC, pyphilia commented on test/fixtures/algorithms/algorithms.js
> +export const GRAASP_ALGORITHMS = [
I know you cannot access the constants because of `getPath`. But let's try to split the file to be able to get these constants.

2020-11-24 13:24 UTC, Painguin commented
Thank you for your review @pyphilia ! 

I like how the tests are setup! It requires us to add a lot of ids and classes to our components only for the tests but I guess it is necessary :laughing:. (One alternative will be to use `client.react$` to access a component [(React Selectors)](https://webdriver.io/docs/selectors.html#react-selectors), but this requires spectron to [support the version 5 of WebdriverIO](https://stackoverflow.com/questions/56843461/how-to-select-a-react-component-with-spectron).
Otherwise I think tests are a good thing to ensure that future changes don't break previous ones.

As you suggested I split the algorithms tests into multiple test files.
I also changed the code when we set the sample database so that it also copies the graasp algorithm files again.

2020-11-24 14:41 UTC, pyphilia approved these changes
It would be really great to select react components directly!! But for now we have our ids and classes it's better than nothing x'3 
Looks good to me!!

2020-12-04 13:50 UTC, pyphilia requested changes
Great! Here some comments.

2020-12-04 13:50 UTC, pyphilia commented on public/app/config/graaspAlgorithms.js
> +  {
Just wondering, don't these algorithm need a type?

2020-12-04 13:50 UTC, pyphilia commented on public/app/db.js
> +    if (!fs.existsSync(ALGORITHMS_FOLDER)) {
I think you can  refactor it with `fs-extra` and `ensureDirSync` or something similar. There is an example in `test/application.js`

2020-12-04 13:50 UTC, pyphilia commented on public/app/listeners/setSampleDatabase.js
> +    fs.emptyDirSync(ALGORITHMS_FOLDER);
👍

2020-12-04 13:50 UTC, pyphilia commented on test/algorithms/addAlgorithm.test.js
> +      client.setTimeout({ implicit: 0 });
Interesting. What does this do?

2020-12-04 13:50 UTC, pyphilia commented on test/algorithms/addAlgorithm.test.js
> +      await menuGoToAlgorithms(client);
I can refactor this to include it in `commands` if you wish.

2020-12-04 13:50 UTC, pyphilia commented on test/algorithms/addAlgorithm.test.js
> +      const nAlgosPrior = await getNumberOfAlgorithms(client);
Would rename as `nbAlgosPrev`

2020-12-04 13:50 UTC, pyphilia commented on test/algorithms/addAlgorithm.test.js
> +      const nAlgosAfter = await getNumberOfAlgorithms(client);
Rename with `nbAlgosAfter`

2020-12-04 13:56 UTC, Painguin commented on public/app/config/graaspAlgorithms.js
> +  {
true :laughing:

2020-12-04 14:59 UTC, pyphilia approved these changes

2020-12-04 15:06 UTC, merged